### ISSUE TITLE
Add tests for Array.prototype.sort exercises

### ISSUE THREAD

**Issue by stevekinney** [mdn/advanced-js-fundamentals-ck#19]
I think I originally omitted tests for this section because they would have pretty much been the same as using the method itself, but students have been asking why their missing—so, it makes sense to add them in order to avoid confusion.

**Comment by indiesquidge** [comment]
I added tests for `sort` in a PR on the repo we originally worked on in class here https://github.com/turingschool-examples/array-prototype-methods/pulls :)

**Comment by stevekinney** [comment]
Right on.

**Comment by chrisdavidmills** [comment]
Writing tests would make another great article, but I'll shut up about this until you have finished the other stuff ;-)
